### PR TITLE
first version of the spanish tutorial

### PR DESCRIPTION
**Pull request by dballari**
Main tutorial pages translated into spanish. Images not yet translated

### CODE REVIEW

**Comment by BorisPAING** [comment]
Hi David, 

Thank you for the great work.

Github won't let me merge the changes. It says:

```
This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
i18n/es_ES/LC_MESSAGES/home.mo
i18n/es_ES/LC_MESSAGES/home.po
i18n/es_ES/LC_MESSAGES/menu.mo
i18n/es_ES/LC_MESSAGES/menu.po 
```

I investigated into the matter and I think it's because the hash of the commit named "home and foot spanish translation review" changed when I merged it (it seems Github has found appropriate to add my name to the commit, thus changing the hash -_-).

I'm trying to figure out a way to solve the issue without typing the barbaric commands Github is suggesting me.

I'd prefer not to have to make a 3-way merge, so if you have an alternative idea to solve this, please share. 

Thanks!

Boris

**Comment by dballari** [comment]
Hi Boris !

It never happened to me, I don't not know why Git made the hash change, and I'm not sure why a 3 way merge is not an appropiate solution. May be a 3 way merge followed by a commit (if necessary) of the newer versions of these po anb mo files would make it. I'll investigate it further and see if I find a better solution.

Thanks,

David

**Comment by BorisPAING** [comment]
Hi David, 

Sorry for the wait. I just saw a line I hadn't seen previously: 
> Add more commits by pushing to the [master](https://github.com/dballari/cesium_website) branch on [dballari/cesium_website](https://github.com/dballari/cesium_website).

I guess you see it too, don't you?

The following command line instructions now make way more sense to me.

So it looks like it's only on your repository that the collisions can be fixed. Can you fix them and create your PR anew?

Thanks!

Boris

**Comment by dballari** [comment]
Hi Boris, you are right, this makes more sense. I’ll do it and create a new PR.

Thanks,

David

**Comment by dballari** [comment]
I have modifed mo and po files and will create a new PR

**Comment by BorisPAING** [comment]
Alright.

**Pull request closed without merging**
